export const theme = {
  colors: {
    surface: "#F9F9F8",
    onSurface: "#1C1E1C",
    surfaceSecondary: "#FFFFFF",
    onSurfaceSecondary: "#1C1E1C",
    surfaceTertiary: "#F2F2EF",
    onSurfaceTertiary: "#646864",
    surfaceInverse: "#2B2D2B",
    onSurfaceInverse: "#F9F9F8",
    brand: "#5C785A",
    brandPrimary: "#5C785A",
    onBrandPrimary: "#FFFFFF",
    brandSecondary: "#A3B8A6",
    onBrandSecondary: "#1A231B",
    brandTertiary: "#E7EFE8",
    onBrandTertiary: "#293B2B",
    success: "#4A7751",
    onSuccess: "#FFFFFF",
    warning: "#B87B2E",
    onWarning: "#FFFFFF",
    error: "#BA4B45",
    onError: "#FFFFFF",
    info: "#4E706F",
    onInfo: "#FFFFFF",
    border: "#E3E3E0",
    borderStrong: "#D1D1CD",
    divider: "#E3E3E0",
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
    xxxl: 48,
  },
  radius: {
    sm: 6,
    md: 12,
    lg: 20,
    pill: 999,
  },
  font: {
    sm: 12,
    base: 14,
    lg: 16,
    xl: 20,
    xxl: 24,
  },
} as const;

export const API_BASE = process.env.EXPO_PUBLIC_BACKEND_URL + "/api";
